services:
  synth:
    build: .
    image: xargonwan/synthetic_heart:${IMAGE_VERSION:-latest-develop}
    container_name: synth
    hostname: synthetic-heart

    env_file:
      - .env

    ports:
      - "0.0.0.0:${SYNTH_WEBUI_HTTPS_PORT:-8000}:${SYNTH_WEBUI_HTTPS_PORT:-8000}"
      - "0.0.0.0:${SYNTH_WEBUI_HTTP_PORT:-8080}:${SYNTH_WEBUI_HTTP_PORT:-8080}"
      - "0.0.0.0:${SELKIES_HTTPS_PORT:-3006}:3001"
      - "0.0.0.0:${OLLAMA_PORT:-11434}:11434"

    volumes:
      - synth_data:/config
      - synth_skins:/app/skins

      # Map local ./logs folder so you can see them
      - ./logs:/app/logs
      # - synth_logs:/app/logs

      # Dev mounts (optional, keep if you edit code live)
      - ./plugins:/app/plugins
      - ./interface:/app/interface

    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}

      - DB_HOST=${DB_HOST:-synth-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-synth}
      - DB_PASS=${DB_PASS:-synth}
      - DB_NAME=${DB_NAME:-synth}
      - DB_ROOT_PASS=${DB_ROOT_PASS:-root}
      - ROOT_PASSWORD=${ROOT_PASSWORD:-"password"}
      - SYNTH_WEBUI_HTTPS_PORT=${SYNTH_WEBUI_HTTPS_PORT:-8000}
      - SYNTH_WEBUI_HTTP_PORT=${SYNTH_WEBUI_HTTP_PORT:-8080}

    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - synth-db
    networks:
      - synth_network

  synth-db:
    container_name: synth-db
    hostname: synth-db
    image: mariadb:11
    ports:
      - "${EXT_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-root}
      MYSQL_DATABASE: ${DB_NAME:-synth}
      MYSQL_USER: ${DB_USER:-synth}
      MYSQL_PASSWORD: ${DB_PASS:-synth}
      MARIADB_AUTO_UPGRADE: 1
    command: --max-connections=200
    volumes:
      - synth_db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - synth_network

  synth-db-backup:
    container_name: synth-db-backup
    image: tiredofit/db-backup
    depends_on:
      - synth-db
    environment:
      DB_TYPE: mysql
      DB_HOST: ${DB_HOST:-synth-db}
      DB_NAME: ${DB_NAME:-synth}
      DB_USER: ${DB_USER:-synth}
      DB_PASS: ${DB_PASS:-synth}
      DB_DUMP_FREQ: 60
      DB_CLEANUP_TIME: 1440
      CONTAINER_TIMEZONE: ${TZ:-UTC}
      COMPRESSION: GZ
      DB_DUMP_TARGET: /backup
    volumes:
      - ./backups:/backup
    restart: unless-stopped
    networks:
      - synth_network

volumes:
  synth_db_data:
  synth_data:
  synth_logs:
  synth_skins:


networks:
  synth_network:
    driver: bridge
    name: synth_network
